<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'HookConphig' => 'src/HookConphig.php'
  ),
  'function' => array(
    'endsWith' => 'src/HookConphig.php',
  ),
  'xmap' => array(
    'HookConphig' => 'ArcanistConfiguration'
  ),
));
